# Generated by Django 3.2.11 on 2022-04-22 23:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aziende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partita_iva', models.CharField(max_length=80, null=True, unique=True)),
                ('ragione_sociale', models.CharField(max_length=200)),
                ('tutor_referente_azienda', models.CharField(blank=True, max_length=200, null=True)),
                ('sede_comune', models.CharField(max_length=200, null=True)),
                ('sede_provincia', models.CharField(max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('settore', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['ragione_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('classi', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contatti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('responsabile', models.CharField(blank=True, max_length=100, null=True)),
                ('num_studenti', models.IntegerField(default=0)),
                ('periodo_da', models.DateField(blank=True, null=True)),
                ('periodo_a', models.DateField(blank=True, null=True)),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pcto.aziende', to_field='partita_iva')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcto.tutor')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
