# Generated by Django 3.2.11 on 2022-05-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatti',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcto.tutor', to_field='email'),
        ),
        migrations.AlterField(
            name='Abbinamenti',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcto.aziende', to_field='partita_iva')),
                
        migrations.AddField(
            model_name='aziende',
            name='stagisti',
            field=models.ManyToManyField(through='pcto.Abbinamenti', to='pcto.Studenti'),
        ),
    ]
