# Generated by Django 3.2.11 on 2022-05-15 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('classe', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Abbinamenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_da', models.DateField(blank=True, null=True)),
                ('periodo_a', models.DateField(blank=True, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcto.aziende')),
                ('contatto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pcto.contatti')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcto.studenti')),
            ],
        ),
        migrations.AddField(
            model_name='aziende',
            name='stagisti',
            field=models.ManyToManyField(through='pcto.Abbinamenti', to='pcto.Studenti'),
        ),
    ]
