# Generated by Django 3.2.11 on 2022-04-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatti',
            name='num_studenti',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contatti',
            name='periodo_a',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contatti',
            name='periodo_da',
            field=models.DateField(blank=True, null=True),
        ),
    ]
