# Generated by Django 3.2.11 on 2022-06-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
                ('classe', models.CharField(max_length=200)),
                ('indirizzo', models.CharField(max_length=200)),
                ('anno_corso', models.CharField(max_length=200)),
                ('ragione_sociale', models.CharField(max_length=200)),
                ('sede_indirizzo', models.CharField(max_length=200)),
                ('sede_provincia', models.CharField(max_length=200)),
                ('tutor_scuola', models.CharField(blank=True, max_length=200, null=True)),
                ('tutor_azienda', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
