# Generated by Django 3.2.11 on 2022-04-22 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcto', '0002_auto_20220421_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatti',
            name='azienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcto.aziende'),
        ),
    ]
