# Generated by Django 3.2.11 on 2022-05-15 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcto', '0002_auto_20220515_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatti',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcto.tutor', to_field='email'),
        ),
    ]
