# Generated by Django 3.2.11 on 2022-04-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcto', '0002_studenti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abbinamenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_da', models.DateField(blank=True, null=True)),
                ('periodo_a', models.DateField(blank=True, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcto.aziende')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcto.studenti')),
            ],
        ),
        migrations.AddField(
            model_name='aziende',
            name='stagisti',
            field=models.ManyToManyField(through='pcto.Abbinamenti', to='pcto.Studenti'),
        ),
    ]
