# Generated by Django 3.2.11 on 2022-05-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcto', '0003_alter_contatti_tutor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contatti',
            unique_together={('data', 'azienda')},
        ),
    ]
