# Generated by Django 3.2.11 on 2022-04-24 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcto', '0003_auto_20220423_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='abbinamenti',
            name='contatto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pcto.contatti'),
        ),
    ]
