# Generated by Django 3.2.11 on 2022-04-22 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcto', '0004_alter_contatti_azienda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatti',
            options={'ordering': ['-data']},
        ),
    ]
