# Generated by Django 3.2.11 on 2022-05-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcto', '0004_alter_contatti_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contatti',
            unique_together={('data', 'tutor')},
        ),
    ]
