# Generated by Django 3.2.11 on 2022-05-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcto', '0005_alter_contatti_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abbinamenti',
            name='contatto',
        ),
        migrations.AlterUniqueTogether(
            name='contatti',
            unique_together=set(),
        ),
    ]
