# Generated by Django 3.2 on 2023-10-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=30)),
                ('num_studenti', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indirizzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipologie_ente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipologie_proposte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Studenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientamento.classi')),
            ],
        ),
        migrations.CreateModel(
            name='Proposte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_progetto', models.CharField(max_length=100)),
                ('disciplina', models.CharField(blank=True, max_length=100, null=True)),
                ('max_alunni', models.IntegerField(blank=True, null=True)),
                ('classi_consigliate', models.CharField(blank=True, max_length=100, null=True)),
                ('ente', models.CharField(max_length=100)),
                ('referente_esterno', models.CharField(max_length=100)),
                ('email_ref_esterno', models.CharField(max_length=50)),
                ('tel_ref_esterno', models.CharField(max_length=50)),
                ('data_inizio', models.CharField(blank=True, max_length=20, null=True)),
                ('data_fine', models.CharField(blank=True, max_length=20, null=True)),
                ('indirizzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientamento.indirizzi')),
                ('tipo_ente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientamento.tipologie_ente')),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientamento.tipologie_proposte')),
            ],
        ),
        migrations.AddField(
            model_name='classi',
            name='indirizzo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientamento.indirizzi'),
        ),
    ]
