# Generated by Django 3.2 on 2023-10-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposte',
            name='nome_progetto',
            field=models.CharField(max_length=250),
        ),
    ]
