# Generated by Django 3.2 on 2023-10-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_proposte_nome_progetto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposte',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposte',
            name='num_ore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposte',
            name='valido_pcto',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposte',
            name='email_ref_esterno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proposte',
            name='ente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proposte',
            name='indirizzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.indirizzi'),
        ),
        migrations.AlterField(
            model_name='proposte',
            name='referente_esterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proposte',
            name='tel_ref_esterno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proposte',
            name='tipo_ente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.tipologie_ente'),
        ),
    ]
