# Generated by Django 3.2 on 2023-10-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20231006_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposte',
            name='tipologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.tipologie_proposte'),
        ),
    ]
