# Generated by Django 3.2 on 2023-10-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20231007_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='classi',
            name='docenti_coinvolti',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
