# Generated by Django 3.2 on 2023-10-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_classi_docenti_coinvolti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='classi',
        ),
    ]
