# Generated by Django 3.2 on 2023-10-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_remove_tutor_classi'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposte',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
