# Generated by Django 3.2 on 2023-10-08 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_studenti_tutor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classi',
            options={'ordering': ['classe']},
        ),
        migrations.CreateModel(
            name='Adesioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.proposte')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.studenti')),
            ],
        ),
    ]
