# Generated by Django 3.2 on 2023-10-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_auto_20231008_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposte',
            name='referenti_interni',
            field=models.ManyToManyField(blank=True, to='tutor.Tutor'),
        ),
    ]
