# Generated by Django 3.2 on 2023-10-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_proposte_referenti_interni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposte',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='studenti',
            options={'ordering': ['cognome', 'nome']},
        ),
        migrations.AddField(
            model_name='proposte',
            name='iscrizioni',
            field=models.ManyToManyField(blank=True, to='tutor.Studenti'),
        ),
        migrations.DeleteModel(
            name='Adesioni',
        ),
    ]
