# Generated by Django 3.2 on 2023-10-17 03:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0016_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='testo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
