# Generated by Django 3.2 on 2023-10-17 15:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0018_proposte_allegato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposte',
            name='descrizione',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
