# Generated by Django 3.2 on 2023-10-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0019_alter_proposte_descrizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposte',
            name='luogo',
            field=models.IntegerField(choices=[(0, 'A Scuola'), (1, 'Esterno'), (2, 'Da definire')], default=2),
        ),
    ]
