# Generated by Django 3.2 on 2023-10-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0020_proposte_luogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposte',
            name='indirizzo',
        ),
        migrations.AddField(
            model_name='proposte',
            name='indirizzo',
            field=models.ManyToManyField(blank=True, to='tutor.Indirizzi'),
        ),
    ]
