# Generated by Django 3.2 on 2023-10-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0021_auto_20231019_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposte',
            name='attivo',
            field=models.BooleanField(default=True),
        ),
    ]
