# Generated by Django 3.2 on 2023-11-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0022_proposte_attivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipologia_attivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etichetta', models.CharField(max_length=30)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attivita_tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('durata', models.IntegerField()),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.tipologia_attivita')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor')),
            ],
            options={
                'ordering': ['data', 'tutor'],
            },
        ),
    ]
