# Generated by Django 3.2 on 2023-11-17 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0024_target_attivita'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita_tutor',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='tutor.target_attivita'),
        ),
        migrations.AddField(
            model_name='attivita_tutor',
            name='titolo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
