# Generated by Django 3.2 on 2023-11-22 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0025_auto_20231117_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attivita_tutor',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='attivita_tutor',
            name='tipologia',
        ),
        migrations.AddField(
            model_name='attivita_tutor',
            name='tipologia',
            field=models.ManyToManyField(to='tutor.Tipologia_attivita'),
        ),
    ]
