# Generated by Django 3.2 on 2023-11-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0026_auto_20231122_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attivita_tutor',
            name='tipologia',
            field=models.ManyToManyField(blank=True, to='tutor.Tipologia_attivita'),
        ),
    ]
