# Generated by Django 5.0.6 on 2025-01-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('assenze', models.TextField(blank=True)),
                ('eventi', models.TextField(blank=True)),
                ('uscite', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
