# Generated by Django 5.0.6 on 2025-01-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
