# Generated by Django 4.1.1 on 2023-09-08 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questionari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "luogo",
                    models.IntegerField(
                        choices=[
                            (0, "Villa Reale"),
                            (1, "Villasanta"),
                            (2, "Villa Mirabello"),
                        ],
                        default="0",
                    ),
                ),
                (
                    "intervistatore",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "intervistato",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
            ],
            options={
                "ordering": ["luogo", "data"],
            },
        ),
        migrations.CreateModel(
            name="Domande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testo", models.CharField(max_length=200)),
                ("risposta", models.TextField(blank=True, null=True)),
                (
                    "questionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="festival.questionari",
                    ),
                ),
            ],
        ),
    ]
