# Generated by Django 4.1.1 on 2023-09-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domande",
            name="questionario",
        ),
        migrations.RemoveField(
            model_name="domande",
            name="risposta",
        ),
        migrations.CreateModel(
            name="Risposte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risposta", models.TextField(blank=True, null=True)),
                (
                    "domanda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="festival.domande",
                    ),
                ),
                (
                    "questionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="festival.questionari",
                    ),
                ),
            ],
        ),
    ]
