# Generated by Django 4.1.1 on 2023-09-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0003_alter_domande_options_domande_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="risposte",
            name="domanda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="festival.domande"
            ),
        ),
        migrations.AlterField(
            model_name="risposte",
            name="questionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="festival.questionari"
            ),
        ),
    ]
