# Generated by Django 3.2 on 2023-10-17 18:43

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autore', models.CharField(blank=True, default='admin', max_length=100, null=True)),
                ('data', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('titolo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('testo', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
