# Generated by Django 3.2 on 2023-10-21 06:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('openday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=80, null=True)),
                ('sigla', models.CharField(max_length=30)),
                ('titolo', models.CharField(blank=True, max_length=100, null=True)),
                ('descrizione', ckeditor.fields.RichTextField()),
                ('luogo', models.CharField(blank=True, default='scuola', max_length=100, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('referente', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitatori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(max_length=100)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('ruolo', models.IntegerField(blank=True, choices=[(0, 'genitore'), (1, 'studente'), (2, 'docente')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Iscrizioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_iscrizione', models.DateTimeField(default=django.utils.timezone.now)),
                ('presente', models.BooleanField(blank=True, default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openday.eventi')),
                ('visitatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openday.visitatori')),
            ],
        ),
    ]
