# Generated by Django 3.2 on 2023-10-21 08:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openday', '0002_eventi_iscrizioni_visitatori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitatori',
            name='telefono',
        ),
        migrations.AddField(
            model_name='visitatori',
            name='comune',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='visitatori',
            name='scuola',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='eventi',
            name='descrizione',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='visitatori',
            name='ruolo',
            field=models.IntegerField(blank=True, choices=[(0, 'genitore'), (1, 'studente'), (2, 'docente')], default=0, null=True),
        ),
    ]
