# Generated by Django 3.2 on 2023-10-22 12:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openday', '0004_auto_20231021_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, max_length=50, null=True)),
                ('descrizione', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
