# Generated by Django 3.2 on 2023-10-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openday', '0005_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='immagine',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
