# Generated by Django 3.2 on 2023-10-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openday', '0006_gallery_immagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
