# Generated by Django 3.2 on 2023-10-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openday', '0007_gallery_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='immagine',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
