# Generated by Django 3.2 on 2023-10-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openday', '0008_alter_gallery_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='immagine',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
